### PR TITLE
Upgraded Distributions version 0.23->0.24

### PR DESCRIPTION
**Pull request by GuillaumeLam**
Ran into a compatibility issue with ReinforcementLearning.jl as shown in: https://www.gitmemory.com/issue/JuliaReinforcementLearning/ReinforcementLearning.jl/301/848546142

Upgrading Distributions.jl to version 0.24 solves this issue so I changed the compact version and test seem to run fine! This change will allow me to use SNN with RL. :)

### CODE REVIEW

**Comment by SBuercklin** [comment]
Hey, thanks for finding a solution to this! If you remove the compat bound entirely, does it still work? The compatibility requirements might be unnecessary, I'll give it a look this afternoon.

**Comment by GuillaumeLam** [comment]
Hello! The tests and lib seem to all work as indented without the compat bound! Initially, I did not want to change more than necessary. 

On a side note about the scope of the lib, I was interested in coding a Liquid State Machine (basically an Echo State Network but with SNN). I am currently coding up a poisson neuron to interpret values from an RL environement. Would this fit in the scope of the WaspNet codebase or would you recommend that I build another library? Thanks again!

**Comment by SBuercklin** [comment]
If you want to add some neuron types to the core library and have a generic implementation, I think it's worth adding with some tests if possible. I haven't worked on this project in a while, but I'm happy to do some house-cleaning too (like removing the Manifest.toml, that doesn't need to be there). Open some issues if you want to discuss further features and I'll see about working on this when I get the time.

**Comment by SBuercklin** [comment]
I updated the `compat` bounds and pushed a new version, `v0.1.3`. This should address your change. 

Thanks for pointing this out, I'll try to get out ahead of CompatHelperBot in the future and merge those branches more promptly.

Release notes here: https://github.com/leaflabs/WaspNet.jl/releases/tag/v0.1.3

**Pull request closed without merging**
